spring.datasource.url=jdbc:postgresql://localhost:5432/financedb
spring.datasource.username=postgres
spring.datasource.password=118820
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.forward-headers-strategy=framework
api.security.token.secret=${JWT_SECRET:8f3a92c1e6b74d05f9a1c3e8b2d6f4a09c7e5b3d1f8a6c4e2b9d7f5a3c1e8b6d}